# CONFIG_BT_LL_SW_LLCP_LEGACY=y

CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
CONFIG_BT_BUF_ACL_TX_COUNT=32
CONFIG_BT_L2CAP_TX_BUF_COUNT=32

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 启用显示屏功能
CONFIG_ZMK_DISPLAY=y

# 启用 GC9A01 驱动 (若 ZMK 有此选项)
CONFIG_GC9A01=y

# 启用 PWM (背光，不接 BLK 时可省略)
CONFIG_PWM=y

# 空闲自动息屏 (可选)
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=30000



# 启用键盘RGB功能
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3




